[metadata]
name = MSquantSim
version = 0.0.1
description = MSquantSim: utilities for MS proteomics simulation and analysis
long_description = file: README.md
long_description_content_type = text/markdown
author = devonjkohler
license = MIT
license_files = LICENSE
classifiers =
    Programming Language :: Python :: 3
    Operating System :: OS Independent

[options]
packages = find:
package_dir =
    = src
include_package_data = True
python_requires = >=3.8
install_requires =
    copulas
    matplotlib
    networkx
    numpy
    pandas
    scikit-learn
    scipy
    sdv
    seaborn
    table_evaluator
    tqdm_joblib
    protmapper
    indra
    
[options.packages.find]
where = src
